#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# SConstruct  (Madagascar Script)
#
# Purpose: Parameters test of VFSA process.
#
# Site: https://dirack.github.io
# 
# Version 1.0
#
# Programer: Rodolfo A. C. Neves (Dirack) 10/11/2020
#
# Email: rodolfo_profissional@hotmail.com
#
# License: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

# Madagascar library
from rsf.proj import *

s="surface"
Flow(s,s+'.asc','dd type=float form=native | smooth rect1=5 rect2=5 repeat=2')

Result(s,'grey color=j scalebar=y title=Semblance')

End()
