name:   CI tests

on:
        push:
                branches:
                        - "feature/*"
                        - "hotfix/*"
                        - "documentation/*"
                        - "test/*"
        workflow_dispatch:
                branches:
                        - "feature/*"
                        - "hotfix/*"
                        - "documentation/*"
                        - "test/*"

jobs:
        build:
                uses: ./.github/workflows/tests.yml 
        test:
                uses: ./.github/workflows/tests.yml 
