name:   CI tests

on:
        push:
                branches:
                        - "master"
        pull_request:
                branches:
                        - "master"
        workflow_dispatch:
                branches:
                        - "develop/*"

jobs:
        test:
                runs-on: ubuntu-latest

                steps:
                        - uses: actions/checkout@v3

                        - name: Build docker image and test - Madagascar Environment
                          run: |
                                  echo "Build the image in the Dockerfile and call 'make -C test' to run all the tests"
                                  docker build . --file Dockerfile
