name:   CI tests

on:
        workflow_dispatch:
                branches:
                        - "develop/2.0.2"

jobs:
        test:
                runs-on: ubuntu-latest

                steps:
                        - uses: actions/checkout@v3

                        - name: Test
                          run: make -C test TESTS=libraries
