name:   CI tests

on:
        push:
                branches:
                        - "master"
        pull_request:
                branches:
                        - "master"
        workflow_dispatch:
                branches:
                        - "develop/*"

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - name: Repository checkout
                          uses: actions/checkout@v3

                        - name: Set up Docker Buildx
                          uses: docker/setup-buildx-action@v1

                        - name: Build and push
                          uses: docker/build-push-action@v2
                          with:
                                context: .
                                file: ./Dockerfile
                                tags: testimage:latest
                                outputs: type=docker,dest=/tmp/testimage.tar

                        - name: Upload artifact
                          uses: actions/upload-artifact@v2
                          with:
                                name: testimage
                                path: /tmp/testimage.tar

        test:
                runs-on: ubuntu-latest
                needs: build
                steps:
                        - name: Ccheck
                          uses: actions/checkout@v3

                        - name: Build test image
                          run: docker build . -f Dockerfile -t testeimage:0.1.0

                        - name: Build docker image and run tests
                          run: docker run -t testeimage:0.1.0 ls

                        - name: Build docker image and run tests
                          run: docker run -t testeimage:0.1.0 echo oi
