name:   CI tests

on:
        push:
                branches:
                        - "master"
        pull_request:
                branches:
                        - "master"
        workflow_dispatch:
                branches:
                        - "develop/*"

jobs:
        checkout:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Repository checkout
                          run: ls
        test:
                runs-on: ubuntu-latest
                needs: checkout
                steps:
                        - name: Ccheck
                          uses: actions/checkout@v3

                        - name: Build docker image and run tests
                          uses: ghcr.io/dirack/madagascarenvironment:1.0.1
                          run: |
                                  echo "Build the image in the Dockerfile and call 'make -C test' to run all the tests"

