name:   CI tests

on:
        workflow_dispatch:
                branches:
                        - "develop/2.0.2"

jobs:
        test:
                runs-on: ubuntu-latest
                container:
                        image: ghcr.io/dirack/madagascarenvironment:1.0.0
                        volumes:
                                - /home/tryitondocker/madagascar-3.0/user/vfsa:.

                steps:
                        - uses: actions/checkout@v3

                        - name: Test
                          run: make -C test TESTS=libraries
