name:   CI tests on a container

on:
        push:
                branches:
                        - "master"
        pull_request:
                branches:
                        - "master"
        workflow_dispatch:
                branches:
                        - "develop/*"

jobs:
        test:
                runs-on: ubuntu-latest
                container:
                        image: ghcr.io/dirack/madagascarenvironment:1.0.1
                        volumes:
                                - ${{github.workspace}}:/home/tryitondocker/madagascar-3.0/user/vfsa

                steps:
                        - uses: actions/checkout@v3

                        - name: Run standalone tests
                          run: |
                               cd /home/tryitondocker/madagascar-3.0/user/vfsa
                               scons
