name:   CI tests on a container

on:
        push:
                branches:
                        - "master"
        pull_request:
                branches:
                        - "master"
        workflow_dispatch:
                branches:
                        - "develop/*"

jobs:
        test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3

                        - name: Run standalone tests
                          uses: 'ghcr.io/dirack/madagascarenvironment:1.0.1'
                          run: ls
