name:   tests

on: [workflow_call]
 
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - name: Repository checkout
                          uses: actions/checkout@v3

                        - name: Set up Docker Buildx
                          uses: docker/setup-buildx-action@v1

                        - name: Build and push
                          uses: docker/build-push-action@v2
                          with:
                                context: .
                                file: ./infra/docker/Dockerfile
                                tags: testimage:0.1.0
                                outputs: type=docker,dest=/tmp/testimage.tar

                        - name: Upload artifact
                          uses: actions/upload-artifact@v2
                          with:
                                name: testimage
                                path: /tmp/testimage.tar
                                retention-days: 0

        test:
                runs-on: ubuntu-latest
                needs: build
                steps:
                        - name: Set up Docker Buildx
                          uses: docker/setup-buildx-action@v1
                        - name: Download artifact
                          uses: actions/download-artifact@v2
                          with:
                                name: testimage
                                path: /tmp
                        - name: Load Docker image
                          run: |
                               docker load --input /tmp/testimage.tar

                        - name: Run unit tests for VFSA functions
                          run: docker run -t testimage:0.1.0 bash -c "cd /home/tryitondocker/madagascar-3.0/user/vfsa && make -C test TESTS=libraries"
